### ISSUE TITLE
Prompt colour

### ISSUE THREAD

**Issue by giltig** [mridgers/clink#286] opened 2015-01-31 16:45 UTC
![why it changed my color](https://cloud.githubusercontent.com/assets/5754742/5988834/ff98d54c-a979-11e4-9676-e965a0ede152.png)
Hi,
In clink version 0.4.2 prompt color was working fine.
In 0.4.3 it stopped working.
Furthermore when other programs change the color of text (such as sails.js lift) it sticks instead or returning to my defined color.

**Comment by mridgers** [comment] 2015-02-02 21:37
This is a duplicate of #279. Check there for a fix.

**Closed by mridgers** 2015-02-02 21:37 UTC
