### ISSUE TITLE
Command Line No Longer Autocompletes Paths in set PATH=[Tab]

### ISSUE THREAD

**Issue by eddieparker** [mridgers/clink#288] opened 2015-02-06 23:59 UTC
Not sure if this is a known issue or by designed, but in normal windows command prompt, you can do:

set PATH=C:\Pyt 

And if you hit the 'tab' key, it will autocomplete to "Python" if you have said directory.  After installing clink, nothing happens.  Is there a similar way to accomplish that in Clink?

I'm running 0.42, but I didn't see anything that fixed that in .43.  I'll try upgrading shortly.

**Comment by Uxorious** [comment] 2015-02-07 00:00
That one is fixed in 0.43

**Comment by vladimir-kotikov** [comment] 2015-02-07 10:48
Confirm, working in Clink v0.4.3 [git:258fc3]

**Comment by mridgers** [comment] 2015-02-16 22:34
Duplicate of #245.

**Closed by mridgers** 2015-02-16 22:34 UTC
