### ISSUE TITLE
Crash (heap corruption) on cd a directory with exclamation mark

### ISSUE THREAD

**Issue by schlamar** [mridgers/clink#287] opened 2015-02-03 07:15 UTC
When I cd into a directory with an exclamation mark, clink crashes with a heap corruption:

![unbenannt](https://cloud.githubusercontent.com/assets/238652/6016096/c9f52fb2-ab7c-11e4-93bc-133a744b581d.PNG)

![unbenannt1](https://cloud.githubusercontent.com/assets/238652/6016098/ca29577e-ab7c-11e4-86f3-f3dc4df571d2.PNG)

**Comment by mridgers** [comment] 2015-02-03 08:01
This is a duplicate of #283 and was fixed in dcbe8a. There's no release just yet but the Dropbox link in the Readme has a build containing the fix.

**Closed by mridgers** 2015-02-03 08:01 UTC
