### ISSUE TITLE
deadlock on rapid cmd spawning

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#184] opened 2014-02-16 00:53 UTC
_From [jean.phi...@gmail.com](https://code.google.com/u/115227813651841736544/) on February 11, 2014 21:48:28_

I'm compiling code from a cmd.exe window.  My build scripts are spawning cmd.exe processes themselves  (that's part of msbuild actually)

When clink is enabled (with the autorun feature), I frequently get deadlocks (my whole desktop freezes and I can't do anything else then reboot).

Looks like the box is still functioning, but explorer.exe (the window manager portion of it) hangs.

_Original issue: http://code.google.com/p/clink/issues/detail?id=185_

**Comment by jprobichaud** [comment] 2015-07-28 13:48
You can close this one, the dev build back in the days had fixed the issue (I thought I had commented that info back).  Build 0.4.4 definitely work well with the build infra, leading me to think that the issue is indeed resolved.

**Comment by mridgers** [comment] 2015-08-05 06:40
Okay! Thanks for following back up!

**Closed by mridgers** 2015-08-05 06:40 UTC
Labels: bug, imported
