### ISSUE TITLE
Atom package installation failing with autorun enabled

### ISSUE THREAD

**Issue by xasx** [mridgers/clink#375] opened 2016-01-14 08:51 UTC
When clink hooks are installed (`clink autorun install -a`), fetching featured packages is not possible. 

The error I get is
> The system cannot find the path specified.
[original error message in my system's locale, German - thus it must come from the OS]

Displaying the currently installed packages does not work either.
However, using `apm`, everything is fine.

If I `clink autorun uninstall -a` then the fetching and displaying of the packages works again.

Unfortunately, I cannot see which path the OS is unable to find. Can you help me track this down?

I'd love to have clink autorun enabled as well as being able to install Atom packages from within the UI.

**Comment by mridgers** [comment] 2016-01-14 09:30
This is a duplicate of #373 I think?

**Comment by mridgers** [comment] 2016-01-15 09:14
Fixed in 0.4.7.

**Closed by mridgers** 2016-01-15 09:14 UTC

**Comment by xasx** [comment] 2016-01-16 21:13
I'll re-check this with 0.4.7 next week.

**Comment by xasx** [comment] 2016-01-29 09:22
Verified working now.

Thanks again.
